### ISSUE TITLE
AnySearch violates privacy, always contacts Google

### ISSUE THREAD

**Issue by Midar** [mcs07/AnySearch-safari-extension#1]
AnySearch uses - without asking the user and without making it possible to disable it - Google Analytics, a well-known privacy-violating Google service. Thus AnySearch also violates my privacy, making it useless to use AnySearch in order to switch the search engine to a more privacy-friendly one like DuckDuckGo.

**Comment by sundarv85** [comment]
Just curious. I do not see this DoNotTrack branch anymore. Is AnySearch still contacting Google or is it already removed.

**Comment by mcs07** [comment]
Yes, all Google Analytics code has been completely removed from AnySearch, so the DoNotTrack branch is no longer required.
