### ISSUE TITLE
unable to install. file missing from your assets server

### ISSUE THREAD

**Issue by arkarkark** [mcs07/AnySearch-safari-extension#4]
When I try to install from the download button it fails

on this page
http://www.macosxtips.co.uk/extensions/#anysearch

I get a 404 for http://assets.matt-swain.com/extensions/anysearch.safariextz

**Comment by mcs07** [comment]
Is this still the case? Everything appears fine to me.

Releases are also available on GitHub: https://github.com/mcs07/AnySearch-safari-extension/releases

**Comment by arkarkark** [comment]
It's working great now, thanks!

maybe update the README.md to point to the file on github rather than assets.matt-swain.com ?
