### ISSUE TITLE
autocomplete messing it up

### ISSUE THREAD

**Issue by JayBrown** [mcs07/AnySearch-safari-extension#6]
I use AnySearch to disable search from the URL field, because I want to do it with key search instead. The URL bar should be for inputting URLs or accessing history & bookmarks. So first here's a big thank you for providing us with this extension. However, Safari 8.0.8 in 10.10.5 now messes up my URL inputs by auto-completing, adding for example a ".com".

For example, when I enter "en.wikipedia.org/wiki/John Doe" into the URL field, Safari doesn't search for this term anymore at Google, DuckDuckGo etc., which is great, but instead it autocorrects to "en.wikipedia.org/wiki/John%20Doe.com", keeping the space, as "%20", but with a ".com" at the end; Wikipedia then (as usual) autocorrects the %20 to an underdash, in this case to "https://en.wikipedia.org/wiki/John_Doe.com", with an underdash. But the ".com" at the end messes it up, and I end up in a dead end at Wikipedia.

If your extension can disable search via URL bar, you should also add the option to disable URL autocomplete. (If possible.)

**Comment by JayBrown** [comment]
I just looked at your code, and line 5 seems to be the problem, where it says (together with line 4):
---
if (url == 'disable') {
        url = 'http://' + e.query + '.com'
---
You should make the "+ '.com'" an optional addition to the query, depending on the results of a check if the query isn't already a valid URL. Whether you should also add to line 5 some code that replaces [SPACE] for %20 in the user's query, I don't know. (It might be the case that Safari will do that on its own.)

**Comment by mcs07** [comment]
Should now be fixed, thanks for the bug report.
