### ISSUE TITLE
KeySearch in Safari Extensions

### ISSUE THREAD

**Issue by sundarv85** [mcs07/AnySearch-safari-extension#7]
Hello

I do not see the KeySearch extension that is presented in Readme.md in Safari extensions gallery. Is there any reason why that alone is not available.

Thanks

**Comment by mcs07** [comment]
No big reason, I just haven't got around to submitting it. For a while I've been planning to do a big update of KeySearch to fix a bunch of problems and add new features, so I was holding off submitting to the gallery until I do that.

**Comment by sundarv85** [comment]
@mcs07 Looking forward for the KeySearch. Would love to search using key words, which I suppose is not possible with AnySearch
